name: Build, Push and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

  BACKEND_REPOSITORY: ${{ vars.ECR_REPOSITORY_BACKEND }}
  FRONTEND_REPOSITORY: ${{ vars.ECR_REPOSITORY_FRONTEND }}

  IMAGE_TAG: ${{ github.sha }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Application Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPOSITORY:$IMAGE_TAG \
            ./server

      - name: Push Backend Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPOSITORY:$IMAGE_TAG

      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg NGINX_CONFIG=default.k8s.conf \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPOSITORY:$IMAGE_TAG \
            ./client

      - name: Push Frontend Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPOSITORY:$IMAGE_TAG

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.GITOPS_REPOSITORY }}
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update Backend Image
        run: |
          sed -i "s|image: .*studyhub-backend:.*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPOSITORY:$IMAGE_TAG|" \
          gitops/k8s/backend-deployment.yaml

      - name: Update Frontend Image
        run: |
          sed -i "s|image: .*studyhub-frontend:.*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPOSITORY:$IMAGE_TAG|" \
          gitops/k8s/frontend-deployment.yaml

      - name: Commit Changes
        run: |
          cd gitops

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add \
            k8s/backend-deployment.yaml \
            k8s/frontend-deployment.yaml
          
          if git diff --staged --quiet; then
            echo "No deployment manifest changes."
            exit 0
          fi

          git commit -m "ci: deploy $IMAGE_TAG"

          git push origin main